---
- name: create hadoop group
  group:
    name: "{{hadoop_user_name}}"
    state: present

- name: create hadoop user
  user:
    name: "{{hadoop_user_name}}"
    groups: "sudo, {{hadoop_user_name}}"

- name: create hadoop dirs
  file:
    path: "{{item}}"
    owner: "{{hadoop_user_name}}"
    group: "{{hadoop_user_name}}"
    mode: 0750
    state: directory
  with_items:
    - "{{hdfs_datanode_path}}"

# Add a fast check to speed reconfiguration
- stat: path=/opt/hadoop
  register: hadoop_installed

- include: install.yml
  when: not hadoop_installed.stat.exists

- include: configure.yml
