- name: refreshDFSNodes
  command: "{{ hadoop_home }}/bin/hdfs dfsadmin -refreshNodes"
  when: '"master" in hadoop_type_of_node or "namenode" in hadoop_type_of_node'
  ignore_errors: yes
  become: true
  become_user: "{{hadoop_user_name}}"

- name: refreshYarnNodes
  command: "{{ hadoop_home }}/bin/yarn rmadmin -refreshNodes"
  when: '"master" in hadoop_type_of_node or "resourcemanager" in hadoop_type_of_node'
  ignore_errors: yes
  become: true
  become_user: "{{hadoop_user_name}}"
 
- name: reload systemd configuration
  become: yes
  command: systemctl daemon-reload
  listen: reload systemd configuration

# Restart services and ensure they are enabled

- name: restart namenode service
  become: yes
  service: name=hdfs_namenode state=restarted enabled=yes
  listen: restart namenode service
  
- name: restart datanode service
  become: yes
  service: name=hdfs_datanode state=restarted enabled=yes
  listen: restart datanode service


